import type { SistemaRiego, TipoSuelo } from "../types";
import { SISTEMAS_RIEGO, TIPOS_SUELO } from "../types";

export type AgriculturalForm = { fecha_siembra: string; edad_cultivo_meses: string; sistema_riego: SistemaRiego | ""; tipo_suelo: TipoSuelo | ""; ultima_aplicacion_fertilizante: string; variedad_cultivo: string };
type Props = { value: AgriculturalForm; onChange: (value: AgriculturalForm) => void };
const labels: Record<string, string> = { ninguno: "Sin riego", goteo: "Goteo", "aspersión": "Aspersión", gravedad: "Gravedad", otro: "Otro", arcilloso: "Arcilloso", arenoso: "Arenoso", franco: "Franco", limoso: "Limoso" };

export function AgriculturalDetails({ value, onChange }: Props) {
  const set = (key: keyof AgriculturalForm, next: string) => onChange({ ...value, [key]: next });
  return <details className="rounded-xl border border-leaf-100 bg-leaf-50/50 p-3"><summary className="cursor-pointer text-sm font-bold text-leaf-800">Más datos del cultivo <span className="font-normal text-slate-500">(opcionales)</span></summary><div className="mt-4 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold text-slate-700">Fecha de siembra<input type="date" value={value.fecha_siembra} onChange={(event) => set("fecha_siembra", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm" /></label><label className="block text-sm font-semibold text-slate-700">Edad (meses)<input type="number" min="0" max="1200" value={value.edad_cultivo_meses} onChange={(event) => set("edad_cultivo_meses", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm" /></label><label className="block text-sm font-semibold text-slate-700">Sistema de riego<select value={value.sistema_riego} onChange={(event) => set("sistema_riego", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">Sin especificar</option>{SISTEMAS_RIEGO.map((option) => <option key={option} value={option}>{labels[option]}</option>)}</select></label><label className="block text-sm font-semibold text-slate-700">Tipo de suelo<select value={value.tipo_suelo} onChange={(event) => set("tipo_suelo", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">Sin especificar</option>{TIPOS_SUELO.map((option) => <option key={option} value={option}>{labels[option]}</option>)}</select></label><label className="block text-sm font-semibold text-slate-700">Última aplicación de fertilizante<input type="date" value={value.ultima_aplicacion_fertilizante} onChange={(event) => set("ultima_aplicacion_fertilizante", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm" /></label><label className="block text-sm font-semibold text-slate-700">Variedad<input value={value.variedad_cultivo} onChange={(event) => set("variedad_cultivo", event.target.value)} placeholder="Ej. Nacional" className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm" /></label></div></div></details>;
}
