const benefits = [
  { icon: "⌁", title: "Delimita tu parcela", description: "Dibuja el área de tu cultivo directamente sobre el mapa." },
  { icon: "◐", title: "Anticipa el clima", description: "Consulta riesgos de lluvia, humedad y temperatura para tu zona." },
  { icon: "✓", title: "Actúa a tiempo", description: "Recibe precauciones prácticas adaptadas a tu cultivo." },
];

export function Landing() {
  return <div className="min-h-screen overflow-hidden bg-[#f5f7f2] text-slate-800">
    <header className="border-b border-leaf-100 bg-white/90"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-4 lg:px-8"><a href="/" className="flex items-center gap-2 font-display text-xl font-bold text-leaf-900"><span className="grid h-9 w-9 place-items-center rounded-xl bg-leaf-600 text-xl text-white">⌁</span>AgroClima <span className="text-amber-600">IA</span></a><a href="/login" className="rounded-xl border border-leaf-600 px-4 py-2 text-sm font-bold text-leaf-700 transition hover:bg-leaf-50">Ingresar <span aria-hidden="true">→</span></a></div></header>
    <main>
      <section className="relative mx-auto max-w-[1180px] px-5 pb-16 pt-16 lg:px-8 lg:pb-24 lg:pt-24"><div aria-hidden="true" className="absolute right-[-8rem] top-2 h-72 w-72 rounded-full bg-leaf-100/70 blur-3xl" /><div aria-hidden="true" className="absolute bottom-4 left-[-7rem] h-52 w-52 rounded-full bg-amber-100/60 blur-3xl" />
        <div className="relative grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-leaf-700">Portoviejo · Manabí</p><h1 className="mt-4 max-w-3xl font-display text-4xl font-bold tracking-tight text-leaf-900 sm:text-5xl lg:text-6xl">Protege tu cultivo antes de que cambie el clima.</h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-600 sm:text-lg">Convierte el pronóstico de tu parcela en alertas y recomendaciones claras para tomar mejores decisiones en el campo.</p><div className="mt-8 flex flex-wrap items-center gap-4"><a href="/login" className="rounded-xl bg-leaf-600 px-5 py-3.5 text-sm font-bold text-white shadow-sm transition hover:bg-leaf-700">Analizar mi cultivo <span className="ml-1" aria-hidden="true">→</span></a><span className="text-sm text-slate-500">Acceso seguro con código por correo</span></div></div>
          <div className="relative rounded-[2rem] border border-leaf-100 bg-white p-5 shadow-[0_24px_70px_-32px_rgba(23,59,42,.38)] sm:p-7"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.18em] text-leaf-700">Alerta de parcela</p><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">Prevención</span></div><div className="mt-6 rounded-2xl bg-leaf-50 p-5"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-leaf-600 text-xl text-white">☂</span><div><p className="font-display text-2xl font-bold text-leaf-900">Conoce el riesgo</p><p className="mt-1 text-sm text-slate-600">antes de que afecte tu cosecha.</p></div></div><div className="mt-6 grid grid-cols-3 gap-2 text-center text-xs font-semibold text-leaf-900"><div className="rounded-xl bg-white px-2 py-3"><span className="block text-lg">⌖</span>Parcela</div><div className="rounded-xl bg-white px-2 py-3"><span className="block text-lg">≈</span>Clima</div><div className="rounded-xl bg-white px-2 py-3"><span className="block text-lg">✓</span>Acción</div></div></div><p className="mt-5 text-sm leading-6 text-slate-500">AgroClima IA analiza las condiciones de tu zona y las interpreta según el cultivo que selecciones.</p></div>
        </div>
      </section>
      <section className="border-y border-leaf-100 bg-white"><div className="mx-auto max-w-[1180px] px-5 py-14 lg:px-8"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-leaf-700">Una decisión más informada</p><h2 className="mt-3 font-display text-3xl font-bold tracking-tight text-leaf-900">Todo lo esencial para prevenir riesgos climáticos.</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{benefits.map((benefit) => <article key={benefit.title} className="rounded-2xl border border-slate-200 bg-[#f9fbf7] p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-leaf-100 text-lg font-bold text-leaf-700">{benefit.icon}</span><h3 className="mt-5 font-display text-xl font-bold text-leaf-900">{benefit.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{benefit.description}</p></article>)}</div></div></section>
    </main>
    <footer className="mx-auto max-w-[1180px] px-5 py-6 text-sm text-slate-500 lg:px-8">AgroClima IA · Prevención climática para productores de Manabí</footer>
  </div>;
}
